// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enableVerticalTabs": boolean;
      "enableHorizontalTabEnhance": boolean;
      "enableCopyReference": boolean;
      "enableGoToAttachment": boolean;
      "enableReloadTab": boolean;
      "verticalTabTitleMode": string;
      "verticalTabSubtitleMode": string;
      "groupColor1": string;
      "groupColor2": string;
      "groupColor3": string;
      "groupColor4": string;
      "groupColor5": string;
      "groupColor6": string;
    };
  }
}
